GH-44: Fix a malloc error when providing the bakcup's path
qustodio/libimobiledevice-node pull request #30
Opened 2021-12-20 14:41 UTC by didix21

2021-12-20 16:22 UTC, irikuo approved these changes
LGTM

2021-12-21 06:14 UTC, jesusmaloQ requested changes
The proposal should be rejected. Poor error handling.

2021-12-21 06:14 UTC, jesusmaloQ commented on src/binding.cc
> +        strncpy(str, *string, string.length() + 1);
The value of str could be null if malloc fails, so this code could generate a SIGSEGV. Fix it.

2021-12-21 07:05 UTC, didix21 commented on src/binding.cc
> +        strncpy(str, *string, string.length() + 1);
Right, I fix it. Thanks

2021-12-21 08:23 UTC, jesusmaloQ requested changes

2021-12-21 08:23 UTC, jesusmaloQ commented on src/binding.cc
> +        char *str = (char *) malloc(string.length() + 1);
The argument to malloc should be `sizeof(char) * (string.length() + 1)`

2021-12-21 10:02 UTC, merged